version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:12.9.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cf:e5:f6:39:98:d3:56:b5:3a:86:5b:7c:4d:a7:d0:eb"
      - checkout
      - run: npm install
      - run: npm run build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'develop' ]; then
              bash .circleci/setup-github.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy
