version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:12.9.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'develop' ]; then
              bash .circleci/setup-github.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy
